---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cas-service
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cas-service
      version: latest
  template:
    metadata:
      name: cas-service-pod
      labels:
        app: cas-service
        version: latest
    spec:
      containers:
      - name: cas-service
        image: 10.10.10.32:5000/cas-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: cas-service-svc
  labels:
    app: cas-service
spec:
  selector:
    app: cas-service
    version: latest
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80
