---    
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: cloud-eureka-deployment
  labels:
    app: cloud
spec:
  selector:
    matchLabels:
      app: cloud
      component: eureka
  replicas: 1
  template: 
    metadata:
      labels:
        app: cloud
        component: eureka
    spec:
      containers:
      - env:
        - name: CONFIGSERVER_HOST
          value: configserver-service
        name: eureka
        image: "10.10.10.32:5000/eureka-service:1.0.0.33"
        imagePullPolicy: Always
        ports:
        - containerPort: 8301
        livenessProbe:
          httpGet:
            path: /health
            port: 8301
          initialDelaySeconds: 300
          periodSeconds: 60
          timeoutSeconds: 2
          failureThreshold: 2
        resources:
          requests:
            memory: "128M"
            cpu: "0.2"
          limits:
            memory: "256M"
            cpu: "0.4"
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: cloud
spec:
  type: NodePort
  selector:
    app: cloud
    component: eureka
  ports:
  - port: 8301
    targetPort: 8301
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-blue-whale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-whale-app
      version: blue
  template:
    metadata:
      name: hello-blue-whale-pod
      labels:
        app: hello-whale-app
        version: blue
    spec:
      containers:
      - name: hello-whale-container
        image: ma7moudhalim/hellowhale:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: hello-whale-svc
  labels:
    app: hello-whale-app
spec:
  selector:
    app: hello-whale-app
    version: blue
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80
